# Generated by Django 4.1.4 on 2022-12-11 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('technologies', models.CharField(max_length=100)),
                ('www', models.CharField(max_length=50)),
                ('base_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='jobsee.baselocation')),
            ],
        ),
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seniority_level', models.CharField(choices=[('1', 'Entry Level'), ('2', 'Junior'), ('3', 'Medior'), ('4', 'Senior')], max_length=1)),
                ('tech_requested', models.CharField(max_length=100)),
                ('tech_nice_to_have', models.CharField(blank=True, max_length=100, null=True)),
                ('work_from', models.CharField(choices=[('1', 'On site'), ('2', 'Hybrid'), ('3', 'Remote')], max_length=1)),
                ('discover_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_adverts', to='jobsee.company')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='jobsee.jobadvert')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='jobsee.company')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('1', 'User'), ('2', 'Company')], max_length=1)),
                ('date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='jobsee.company')),
            ],
        ),
    ]
